server:
  port: 8001

spring:
  application:
    name: springcloud-eureka-client-provider

  datasource:
    name: zhigoumao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: zhigoumao

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ph.springcloud.entity

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-eureka-client-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: springcloud-eureka-client-provider
  company.name: www.phtech.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

test:
  myname: wangyitest_update123456xxxxyyyzzzaaaBBBBBCCCDDDDDDDD
